import streamlit as st
from gnews import GNews
import requests
from datetime import datetime

# --- SETTINGS ---
st.set_page_config(page_title="AI Daily Brief", page_icon="🗞️", layout="wide")

# This will pull from Streamlit Cloud Secrets
HF_TOKEN = st.secrets.get("HF_TOKEN")
API_URL = "https://api-inference.huggingface.co/models/facebook/bart-large-cnn"

# --- BACKEND LOGIC ---
@st.cache_data(ttl=3600)  # Caches news for 1 hour to stay fast
def fetch_news_data(segments):
    google_news = GNews(language='en', period='1d', max_results=3)
    results = {}
    for topic in segments:
        results[topic] = google_news.get_news(topic)
    return results

def get_summary(text):
    if not HF_TOKEN: return "Add HF_TOKEN to secrets for AI summaries."
    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
    payload = {"inputs": text, "parameters": {"max_length": 60, "min_length": 20}}
    try:
        response = requests.post(API_URL, headers=headers, json=payload, timeout=5)
        return response.json()[0]['summary_text']
    except:
        return "Summary generation skipped (API busy)."

# --- USER INTERFACE ---
st.title("🗞️ AI-Powered Daily News Brief")
st.caption(f"Generated on {datetime.now().strftime('%B %d, %Y')}")

# Sidebar - Requirement: User Preference Management
with st.sidebar:
    st.header("Customize your Feed")
    selected_segments = st.multiselect(
        "Choose Topics:",
        ["Technology", "Business", "Sports", "Politics", "Health", "Entertainment"],
        default=["Technology", "Business"]
    )
    st.divider()
    st.write("🔄 *Default home page loads your interests automatically.*")

# Main Content - Requirement: Section-wise layout & Summaries
if not selected_segments:
    st.warning("Please select at least one news segment in the sidebar.")
else:
    news_feed = fetch_news_data(selected_segments)
    
    for category, articles in news_feed.items():
        st.subheader(f"📍 {category}")
        if not articles:
            st.info(f"No new stories for {category} right now.")
            continue
            
        for art in articles:
            with st.container(border=True):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.markdown(f"**{art['title']}**")
                    # Requirement: Readable Summaries
                    summary = get_summary(art['description'] or art['title'])
                    st.write(f"✨ *AI Summary:* {summary}")
                with col2:
                    st.caption(f"Source: {art['publisher']['title']}")
                    st.link_button("Read Original", art['url'])

st.divider()
st.info("💡 Note: This brief is generated by aggregating multiple sources via GNews and summarized using an open-source BART model.")

